fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  group:
    group_class: App\Entity\SonataUserGroup
    group_manager: sonata.user.orm.group_manager
  service:
    user_manager: sonata.user.orm.user_manager
  from_email:
    address: "contact@lamafrance.com"
    sender_name: "contact@lamafrance.com"